-- MySQL schema for anime_bot

CREATE TABLE IF NOT EXISTS anime_datas (
  data_id INT NOT NULL AUTO_INCREMENT,
  id TEXT NOT NULL,
  file_id TEXT NOT NULL,
  qism TEXT NOT NULL,
  sana TEXT,
  PRIMARY KEY (data_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS animelar (
  id INT NOT NULL AUTO_INCREMENT,
  nom TEXT NOT NULL,
  rams TEXT NOT NULL,
  qismi TEXT NOT NULL,
  davlat TEXT NOT NULL,
  tili TEXT NOT NULL,
  yili TEXT NOT NULL,
  janri TEXT NOT NULL,
  qidiruv INT NOT NULL,
  sana TEXT NOT NULL,
  aniType TEXT,
  `like` INT DEFAULT 0,
  deslike INT DEFAULT 0,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS channels (
  id INT NOT NULL AUTO_INCREMENT,
  channelId VARCHAR(32) NOT NULL,
  channelType VARCHAR(255) NOT NULL,
  channelLink VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS joinRequests (
  id INT NOT NULL AUTO_INCREMENT,
  channelId VARCHAR(32) NOT NULL,
  userId VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS kabinet (
  id INT NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(250) NOT NULL,
  pul VARCHAR(250) NOT NULL,
  pul2 VARCHAR(250) NOT NULL,
  odam VARCHAR(250) NOT NULL,
  ban TEXT NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS send (
  send_id INT NOT NULL AUTO_INCREMENT,
  time1 TEXT NOT NULL,
  time2 TEXT NOT NULL,
  start_id TEXT NOT NULL,
  stop_id TEXT NOT NULL,
  admin_id TEXT NOT NULL,
  message_id TEXT NOT NULL,
  reply_markup TEXT NOT NULL,
  step TEXT NOT NULL,
  time3 TEXT NOT NULL,
  time4 TEXT NOT NULL,
  time5 TEXT NOT NULL,
  PRIMARY KEY (send_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS status (
  id INT NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(250) NOT NULL,
  kun VARCHAR(250) NOT NULL,
  date TEXT NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS user_id (
  id INT NOT NULL AUTO_INCREMENT,
  user_id VARCHAR(250) NOT NULL,
  status TEXT NOT NULL,
  refid VARCHAR(11) DEFAULT NULL,
  sana VARCHAR(250) NOT NULL,
  PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
